/*
 * This file is generated by jOOQ.
 */
package org.endeavour.queryengine.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.endeavour.queryengine.db.tables.AllergyIntolerance;
import org.endeavour.queryengine.db.tables.Appointment;
import org.endeavour.queryengine.db.tables.Concept;
import org.endeavour.queryengine.db.tables.ConceptMap;
import org.endeavour.queryengine.db.tables.DiagnosticOrder;
import org.endeavour.queryengine.db.tables.Encounter;
import org.endeavour.queryengine.db.tables.EpisodeOfCare;
import org.endeavour.queryengine.db.tables.EventLog;
import org.endeavour.queryengine.db.tables.Flag;
import org.endeavour.queryengine.db.tables.Location;
import org.endeavour.queryengine.db.tables.MedicationOrder;
import org.endeavour.queryengine.db.tables.MedicationStatement;
import org.endeavour.queryengine.db.tables.Observation;
import org.endeavour.queryengine.db.tables.Organization;
import org.endeavour.queryengine.db.tables.Patient;
import org.endeavour.queryengine.db.tables.PatientAddress;
import org.endeavour.queryengine.db.tables.PatientContact;
import org.endeavour.queryengine.db.tables.PatientUprn;
import org.endeavour.queryengine.db.tables.Person;
import org.endeavour.queryengine.db.tables.Practitioner;
import org.endeavour.queryengine.db.tables.ProcedureRequest;
import org.endeavour.queryengine.db.tables.PseudoId;
import org.endeavour.queryengine.db.tables.ReferralRequest;
import org.endeavour.queryengine.db.tables.Schedule;
import org.endeavour.queryengine.db.tables.TableCounts;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscriberPi extends SchemaImpl {

    private static final long serialVersionUID = -872777232;

    /**
     * The reference instance of <code>subscriber_pi</code>
     */
    public static final SubscriberPi SUBSCRIBER_PI = new SubscriberPi();

    /**
     * The table <code>subscriber_pi.allergy_intolerance</code>.
     */
    public final AllergyIntolerance ALLERGY_INTOLERANCE = org.endeavour.queryengine.db.tables.AllergyIntolerance.ALLERGY_INTOLERANCE;

    /**
     * The table <code>subscriber_pi.appointment</code>.
     */
    public final Appointment APPOINTMENT = org.endeavour.queryengine.db.tables.Appointment.APPOINTMENT;

    /**
     * The table <code>subscriber_pi.concept</code>.
     */
    public final Concept CONCEPT = org.endeavour.queryengine.db.tables.Concept.CONCEPT;

    /**
     * The table <code>subscriber_pi.concept_map</code>.
     */
    public final ConceptMap CONCEPT_MAP = org.endeavour.queryengine.db.tables.ConceptMap.CONCEPT_MAP;

    /**
     * The table <code>subscriber_pi.diagnostic_order</code>.
     */
    public final DiagnosticOrder DIAGNOSTIC_ORDER = org.endeavour.queryengine.db.tables.DiagnosticOrder.DIAGNOSTIC_ORDER;

    /**
     * The table <code>subscriber_pi.encounter</code>.
     */
    public final Encounter ENCOUNTER = org.endeavour.queryengine.db.tables.Encounter.ENCOUNTER;

    /**
     * The table <code>subscriber_pi.episode_of_care</code>.
     */
    public final EpisodeOfCare EPISODE_OF_CARE = org.endeavour.queryengine.db.tables.EpisodeOfCare.EPISODE_OF_CARE;

    /**
     * The table <code>subscriber_pi.event_log</code>.
     */
    public final EventLog EVENT_LOG = org.endeavour.queryengine.db.tables.EventLog.EVENT_LOG;

    /**
     * The table <code>subscriber_pi.flag</code>.
     */
    public final Flag FLAG = org.endeavour.queryengine.db.tables.Flag.FLAG;

    /**
     * The table <code>subscriber_pi.location</code>.
     */
    public final Location LOCATION = org.endeavour.queryengine.db.tables.Location.LOCATION;

    /**
     * The table <code>subscriber_pi.medication_order</code>.
     */
    public final MedicationOrder MEDICATION_ORDER = org.endeavour.queryengine.db.tables.MedicationOrder.MEDICATION_ORDER;

    /**
     * The table <code>subscriber_pi.medication_statement</code>.
     */
    public final MedicationStatement MEDICATION_STATEMENT = org.endeavour.queryengine.db.tables.MedicationStatement.MEDICATION_STATEMENT;

    /**
     * The table <code>subscriber_pi.observation</code>.
     */
    public final Observation OBSERVATION = org.endeavour.queryengine.db.tables.Observation.OBSERVATION;

    /**
     * The table <code>subscriber_pi.organization</code>.
     */
    public final Organization ORGANIZATION = org.endeavour.queryengine.db.tables.Organization.ORGANIZATION;

    /**
     * The table <code>subscriber_pi.patient</code>.
     */
    public final Patient PATIENT = org.endeavour.queryengine.db.tables.Patient.PATIENT;

    /**
     * stores address details for patients
     */
    public final PatientAddress PATIENT_ADDRESS = org.endeavour.queryengine.db.tables.PatientAddress.PATIENT_ADDRESS;

    /**
     * stores contact details (e.g. phone) for patients
     */
    public final PatientContact PATIENT_CONTACT = org.endeavour.queryengine.db.tables.PatientContact.PATIENT_CONTACT;

    /**
     * The table <code>subscriber_pi.patient_uprn</code>.
     */
    public final PatientUprn PATIENT_UPRN = org.endeavour.queryengine.db.tables.PatientUprn.PATIENT_UPRN;

    /**
     * The table <code>subscriber_pi.person</code>.
     */
    public final Person PERSON = org.endeavour.queryengine.db.tables.Person.PERSON;

    /**
     * The table <code>subscriber_pi.practitioner</code>.
     */
    public final Practitioner PRACTITIONER = org.endeavour.queryengine.db.tables.Practitioner.PRACTITIONER;

    /**
     * The table <code>subscriber_pi.procedure_request</code>.
     */
    public final ProcedureRequest PROCEDURE_REQUEST = org.endeavour.queryengine.db.tables.ProcedureRequest.PROCEDURE_REQUEST;

    /**
     * The table <code>subscriber_pi.pseudo_id</code>.
     */
    public final PseudoId PSEUDO_ID = org.endeavour.queryengine.db.tables.PseudoId.PSEUDO_ID;

    /**
     * The table <code>subscriber_pi.referral_request</code>.
     */
    public final ReferralRequest REFERRAL_REQUEST = org.endeavour.queryengine.db.tables.ReferralRequest.REFERRAL_REQUEST;

    /**
     * The table <code>subscriber_pi.schedule</code>.
     */
    public final Schedule SCHEDULE = org.endeavour.queryengine.db.tables.Schedule.SCHEDULE;

    /**
     * The table <code>subscriber_pi.table_counts</code>.
     */
    public final TableCounts TABLE_COUNTS = org.endeavour.queryengine.db.tables.TableCounts.TABLE_COUNTS;

    /**
     * No further instances allowed
     */
    private SubscriberPi() {
        super("subscriber_pi", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AllergyIntolerance.ALLERGY_INTOLERANCE,
            Appointment.APPOINTMENT,
            Concept.CONCEPT,
            ConceptMap.CONCEPT_MAP,
            DiagnosticOrder.DIAGNOSTIC_ORDER,
            Encounter.ENCOUNTER,
            EpisodeOfCare.EPISODE_OF_CARE,
            EventLog.EVENT_LOG,
            Flag.FLAG,
            Location.LOCATION,
            MedicationOrder.MEDICATION_ORDER,
            MedicationStatement.MEDICATION_STATEMENT,
            Observation.OBSERVATION,
            Organization.ORGANIZATION,
            Patient.PATIENT,
            PatientAddress.PATIENT_ADDRESS,
            PatientContact.PATIENT_CONTACT,
            PatientUprn.PATIENT_UPRN,
            Person.PERSON,
            Practitioner.PRACTITIONER,
            ProcedureRequest.PROCEDURE_REQUEST,
            PseudoId.PSEUDO_ID,
            ReferralRequest.REFERRAL_REQUEST,
            Schedule.SCHEDULE,
            TableCounts.TABLE_COUNTS);
    }
}
