/*
 * This file is generated by jOOQ.
 */
package org.endeavour.queryengine.db.tables.records;


import javax.annotation.Generated;

import org.endeavour.queryengine.db.tables.Location;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> implements Record6<Long, String, String, String, String, Long> {

    private static final long serialVersionUID = -1919492652;

    /**
     * Setter for <code>subscriber_pi.location.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>subscriber_pi.location.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>subscriber_pi.location.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>subscriber_pi.location.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>subscriber_pi.location.type_code</code>.
     */
    public void setTypeCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>subscriber_pi.location.type_code</code>.
     */
    public String getTypeCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>subscriber_pi.location.type_desc</code>.
     */
    public void setTypeDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>subscriber_pi.location.type_desc</code>.
     */
    public String getTypeDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>subscriber_pi.location.postcode</code>.
     */
    public void setPostcode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>subscriber_pi.location.postcode</code>.
     */
    public String getPostcode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>subscriber_pi.location.managing_organization_id</code>.
     */
    public void setManagingOrganizationId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>subscriber_pi.location.managing_organization_id</code>.
     */
    public Long getManagingOrganizationId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Location.LOCATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Location.LOCATION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Location.LOCATION.TYPE_CODE;
    }

    @Override
    public Field<String> field4() {
        return Location.LOCATION.TYPE_DESC;
    }

    @Override
    public Field<String> field5() {
        return Location.LOCATION.POSTCODE;
    }

    @Override
    public Field<Long> field6() {
        return Location.LOCATION.MANAGING_ORGANIZATION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getTypeCode();
    }

    @Override
    public String component4() {
        return getTypeDesc();
    }

    @Override
    public String component5() {
        return getPostcode();
    }

    @Override
    public Long component6() {
        return getManagingOrganizationId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getTypeCode();
    }

    @Override
    public String value4() {
        return getTypeDesc();
    }

    @Override
    public String value5() {
        return getPostcode();
    }

    @Override
    public Long value6() {
        return getManagingOrganizationId();
    }

    @Override
    public LocationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public LocationRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LocationRecord value3(String value) {
        setTypeCode(value);
        return this;
    }

    @Override
    public LocationRecord value4(String value) {
        setTypeDesc(value);
        return this;
    }

    @Override
    public LocationRecord value5(String value) {
        setPostcode(value);
        return this;
    }

    @Override
    public LocationRecord value6(Long value) {
        setManagingOrganizationId(value);
        return this;
    }

    @Override
    public LocationRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(Long id, String name, String typeCode, String typeDesc, String postcode, Long managingOrganizationId) {
        super(Location.LOCATION);

        set(0, id);
        set(1, name);
        set(2, typeCode);
        set(3, typeDesc);
        set(4, postcode);
        set(5, managingOrganizationId);
    }
}
