/*
 * This file is generated by jOOQ.
 */
package org.endeavour.queryengine.db.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.endeavour.queryengine.db.tables.MedicationOrder;
import org.jooq.Field;
import org.jooq.Record19;
import org.jooq.Record3;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicationOrderRecord extends UpdatableRecordImpl<MedicationOrderRecord> implements Record19<Long, Long, Long, Long, Long, Long, Date, Integer, String, Double, String, Integer, Double, Long, Integer, Integer, String, BigDecimal, String> {

    private static final long serialVersionUID = 609670622;

    /**
     * Setter for <code>subscriber_pi.medication_order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.organization_id</code>.
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.organization_id</code>.
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.encounter_id</code>.
     */
    public void setEncounterId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.encounter_id</code>.
     */
    public Long getEncounterId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.practitioner_id</code>.
     */
    public void setPractitionerId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.practitioner_id</code>.
     */
    public Long getPractitionerId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.clinical_effective_date</code>.
     */
    public void setClinicalEffectiveDate(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.clinical_effective_date</code>.
     */
    public Date getClinicalEffectiveDate() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.date_precision_concept_id</code>.
     */
    public void setDatePrecisionConceptId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.date_precision_concept_id</code>.
     */
    public Integer getDatePrecisionConceptId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.dose</code>.
     */
    public void setDose(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.dose</code>.
     */
    public String getDose() {
        return (String) get(8);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.quantity_value</code>.
     */
    public void setQuantityValue(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.quantity_value</code>.
     */
    public Double getQuantityValue() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.quantity_unit</code>.
     */
    public void setQuantityUnit(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.quantity_unit</code>.
     */
    public String getQuantityUnit() {
        return (String) get(10);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.duration_days</code>.
     */
    public void setDurationDays(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.duration_days</code>.
     */
    public Integer getDurationDays() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.estimated_cost</code>.
     */
    public void setEstimatedCost(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.estimated_cost</code>.
     */
    public Double getEstimatedCost() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.medication_statement_id</code>.
     */
    public void setMedicationStatementId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.medication_statement_id</code>.
     */
    public Long getMedicationStatementId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.core_concept_id</code>.
     */
    public void setCoreConceptId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.core_concept_id</code>.
     */
    public Integer getCoreConceptId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.non_core_concept_id</code>.
     */
    public void setNonCoreConceptId(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.non_core_concept_id</code>.
     */
    public Integer getNonCoreConceptId() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.bnf_reference</code>.
     */
    public void setBnfReference(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.bnf_reference</code>.
     */
    public String getBnfReference() {
        return (String) get(16);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.age_at_event</code>.
     */
    public void setAgeAtEvent(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.age_at_event</code>.
     */
    public BigDecimal getAgeAtEvent() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>subscriber_pi.medication_order.issue_method</code>.
     */
    public void setIssueMethod(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>subscriber_pi.medication_order.issue_method</code>.
     */
    public String getIssueMethod() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, Long, Long, Long, Long, Long, Date, Integer, String, Double, String, Integer, Double, Long, Integer, Integer, String, BigDecimal, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, Long, Long, Long, Long, Long, Date, Integer, String, Double, String, Integer, Double, Long, Integer, Integer, String, BigDecimal, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MedicationOrder.MEDICATION_ORDER.ID;
    }

    @Override
    public Field<Long> field2() {
        return MedicationOrder.MEDICATION_ORDER.ORGANIZATION_ID;
    }

    @Override
    public Field<Long> field3() {
        return MedicationOrder.MEDICATION_ORDER.PATIENT_ID;
    }

    @Override
    public Field<Long> field4() {
        return MedicationOrder.MEDICATION_ORDER.PERSON_ID;
    }

    @Override
    public Field<Long> field5() {
        return MedicationOrder.MEDICATION_ORDER.ENCOUNTER_ID;
    }

    @Override
    public Field<Long> field6() {
        return MedicationOrder.MEDICATION_ORDER.PRACTITIONER_ID;
    }

    @Override
    public Field<Date> field7() {
        return MedicationOrder.MEDICATION_ORDER.CLINICAL_EFFECTIVE_DATE;
    }

    @Override
    public Field<Integer> field8() {
        return MedicationOrder.MEDICATION_ORDER.DATE_PRECISION_CONCEPT_ID;
    }

    @Override
    public Field<String> field9() {
        return MedicationOrder.MEDICATION_ORDER.DOSE;
    }

    @Override
    public Field<Double> field10() {
        return MedicationOrder.MEDICATION_ORDER.QUANTITY_VALUE;
    }

    @Override
    public Field<String> field11() {
        return MedicationOrder.MEDICATION_ORDER.QUANTITY_UNIT;
    }

    @Override
    public Field<Integer> field12() {
        return MedicationOrder.MEDICATION_ORDER.DURATION_DAYS;
    }

    @Override
    public Field<Double> field13() {
        return MedicationOrder.MEDICATION_ORDER.ESTIMATED_COST;
    }

    @Override
    public Field<Long> field14() {
        return MedicationOrder.MEDICATION_ORDER.MEDICATION_STATEMENT_ID;
    }

    @Override
    public Field<Integer> field15() {
        return MedicationOrder.MEDICATION_ORDER.CORE_CONCEPT_ID;
    }

    @Override
    public Field<Integer> field16() {
        return MedicationOrder.MEDICATION_ORDER.NON_CORE_CONCEPT_ID;
    }

    @Override
    public Field<String> field17() {
        return MedicationOrder.MEDICATION_ORDER.BNF_REFERENCE;
    }

    @Override
    public Field<BigDecimal> field18() {
        return MedicationOrder.MEDICATION_ORDER.AGE_AT_EVENT;
    }

    @Override
    public Field<String> field19() {
        return MedicationOrder.MEDICATION_ORDER.ISSUE_METHOD;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrganizationId();
    }

    @Override
    public Long component3() {
        return getPatientId();
    }

    @Override
    public Long component4() {
        return getPersonId();
    }

    @Override
    public Long component5() {
        return getEncounterId();
    }

    @Override
    public Long component6() {
        return getPractitionerId();
    }

    @Override
    public Date component7() {
        return getClinicalEffectiveDate();
    }

    @Override
    public Integer component8() {
        return getDatePrecisionConceptId();
    }

    @Override
    public String component9() {
        return getDose();
    }

    @Override
    public Double component10() {
        return getQuantityValue();
    }

    @Override
    public String component11() {
        return getQuantityUnit();
    }

    @Override
    public Integer component12() {
        return getDurationDays();
    }

    @Override
    public Double component13() {
        return getEstimatedCost();
    }

    @Override
    public Long component14() {
        return getMedicationStatementId();
    }

    @Override
    public Integer component15() {
        return getCoreConceptId();
    }

    @Override
    public Integer component16() {
        return getNonCoreConceptId();
    }

    @Override
    public String component17() {
        return getBnfReference();
    }

    @Override
    public BigDecimal component18() {
        return getAgeAtEvent();
    }

    @Override
    public String component19() {
        return getIssueMethod();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrganizationId();
    }

    @Override
    public Long value3() {
        return getPatientId();
    }

    @Override
    public Long value4() {
        return getPersonId();
    }

    @Override
    public Long value5() {
        return getEncounterId();
    }

    @Override
    public Long value6() {
        return getPractitionerId();
    }

    @Override
    public Date value7() {
        return getClinicalEffectiveDate();
    }

    @Override
    public Integer value8() {
        return getDatePrecisionConceptId();
    }

    @Override
    public String value9() {
        return getDose();
    }

    @Override
    public Double value10() {
        return getQuantityValue();
    }

    @Override
    public String value11() {
        return getQuantityUnit();
    }

    @Override
    public Integer value12() {
        return getDurationDays();
    }

    @Override
    public Double value13() {
        return getEstimatedCost();
    }

    @Override
    public Long value14() {
        return getMedicationStatementId();
    }

    @Override
    public Integer value15() {
        return getCoreConceptId();
    }

    @Override
    public Integer value16() {
        return getNonCoreConceptId();
    }

    @Override
    public String value17() {
        return getBnfReference();
    }

    @Override
    public BigDecimal value18() {
        return getAgeAtEvent();
    }

    @Override
    public String value19() {
        return getIssueMethod();
    }

    @Override
    public MedicationOrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value2(Long value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value3(Long value) {
        setPatientId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value4(Long value) {
        setPersonId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value5(Long value) {
        setEncounterId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value6(Long value) {
        setPractitionerId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value7(Date value) {
        setClinicalEffectiveDate(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value8(Integer value) {
        setDatePrecisionConceptId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value9(String value) {
        setDose(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value10(Double value) {
        setQuantityValue(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value11(String value) {
        setQuantityUnit(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value12(Integer value) {
        setDurationDays(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value13(Double value) {
        setEstimatedCost(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value14(Long value) {
        setMedicationStatementId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value15(Integer value) {
        setCoreConceptId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value16(Integer value) {
        setNonCoreConceptId(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value17(String value) {
        setBnfReference(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value18(BigDecimal value) {
        setAgeAtEvent(value);
        return this;
    }

    @Override
    public MedicationOrderRecord value19(String value) {
        setIssueMethod(value);
        return this;
    }

    @Override
    public MedicationOrderRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6, Date value7, Integer value8, String value9, Double value10, String value11, Integer value12, Double value13, Long value14, Integer value15, Integer value16, String value17, BigDecimal value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicationOrderRecord
     */
    public MedicationOrderRecord() {
        super(MedicationOrder.MEDICATION_ORDER);
    }

    /**
     * Create a detached, initialised MedicationOrderRecord
     */
    public MedicationOrderRecord(Long id, Long organizationId, Long patientId, Long personId, Long encounterId, Long practitionerId, Date clinicalEffectiveDate, Integer datePrecisionConceptId, String dose, Double quantityValue, String quantityUnit, Integer durationDays, Double estimatedCost, Long medicationStatementId, Integer coreConceptId, Integer nonCoreConceptId, String bnfReference, BigDecimal ageAtEvent, String issueMethod) {
        super(MedicationOrder.MEDICATION_ORDER);

        set(0, id);
        set(1, organizationId);
        set(2, patientId);
        set(3, personId);
        set(4, encounterId);
        set(5, practitionerId);
        set(6, clinicalEffectiveDate);
        set(7, datePrecisionConceptId);
        set(8, dose);
        set(9, quantityValue);
        set(10, quantityUnit);
        set(11, durationDays);
        set(12, estimatedCost);
        set(13, medicationStatementId);
        set(14, coreConceptId);
        set(15, nonCoreConceptId);
        set(16, bnfReference);
        set(17, ageAtEvent);
        set(18, issueMethod);
    }
}
