/*
 * This file is generated by jOOQ.
 */
package org.endeavour.queryengine.db.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.endeavour.queryengine.db.tables.Patient;
import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record3;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientRecord extends UpdatableRecordImpl<PatientRecord> implements Record13<Long, Long, Long, String, String, String, Integer, String, Date, Date, Long, Integer, Long> {

    private static final long serialVersionUID = -1040259158;

    /**
     * Setter for <code>subscriber_pi.patient.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>subscriber_pi.patient.organization_id</code>.
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.organization_id</code>.
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>subscriber_pi.patient.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>subscriber_pi.patient.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>subscriber_pi.patient.first_names</code>.
     */
    public void setFirstNames(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.first_names</code>.
     */
    public String getFirstNames() {
        return (String) get(4);
    }

    /**
     * Setter for <code>subscriber_pi.patient.last_name</code>.
     */
    public void setLastName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>subscriber_pi.patient.gender_concept_id</code>.
     */
    public void setGenderConceptId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.gender_concept_id</code>.
     */
    public Integer getGenderConceptId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>subscriber_pi.patient.nhs_number</code>.
     */
    public void setNhsNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.nhs_number</code>.
     */
    public String getNhsNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>subscriber_pi.patient.date_of_birth</code>.
     */
    public void setDateOfBirth(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.date_of_birth</code>.
     */
    public Date getDateOfBirth() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>subscriber_pi.patient.date_of_death</code>.
     */
    public void setDateOfDeath(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.date_of_death</code>.
     */
    public Date getDateOfDeath() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>subscriber_pi.patient.current_address_id</code>.
     */
    public void setCurrentAddressId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.current_address_id</code>.
     */
    public Long getCurrentAddressId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>subscriber_pi.patient.ethnic_code_concept_id</code>.
     */
    public void setEthnicCodeConceptId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.ethnic_code_concept_id</code>.
     */
    public Integer getEthnicCodeConceptId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>subscriber_pi.patient.registered_practice_organization_id</code>.
     */
    public void setRegisteredPracticeOrganizationId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>subscriber_pi.patient.registered_practice_organization_id</code>.
     */
    public Long getRegisteredPracticeOrganizationId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Long, Long, String, String, String, Integer, String, Date, Date, Long, Integer, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, Long, Long, String, String, String, Integer, String, Date, Date, Long, Integer, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Patient.PATIENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Patient.PATIENT.ORGANIZATION_ID;
    }

    @Override
    public Field<Long> field3() {
        return Patient.PATIENT.PERSON_ID;
    }

    @Override
    public Field<String> field4() {
        return Patient.PATIENT.TITLE;
    }

    @Override
    public Field<String> field5() {
        return Patient.PATIENT.FIRST_NAMES;
    }

    @Override
    public Field<String> field6() {
        return Patient.PATIENT.LAST_NAME;
    }

    @Override
    public Field<Integer> field7() {
        return Patient.PATIENT.GENDER_CONCEPT_ID;
    }

    @Override
    public Field<String> field8() {
        return Patient.PATIENT.NHS_NUMBER;
    }

    @Override
    public Field<Date> field9() {
        return Patient.PATIENT.DATE_OF_BIRTH;
    }

    @Override
    public Field<Date> field10() {
        return Patient.PATIENT.DATE_OF_DEATH;
    }

    @Override
    public Field<Long> field11() {
        return Patient.PATIENT.CURRENT_ADDRESS_ID;
    }

    @Override
    public Field<Integer> field12() {
        return Patient.PATIENT.ETHNIC_CODE_CONCEPT_ID;
    }

    @Override
    public Field<Long> field13() {
        return Patient.PATIENT.REGISTERED_PRACTICE_ORGANIZATION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrganizationId();
    }

    @Override
    public Long component3() {
        return getPersonId();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getFirstNames();
    }

    @Override
    public String component6() {
        return getLastName();
    }

    @Override
    public Integer component7() {
        return getGenderConceptId();
    }

    @Override
    public String component8() {
        return getNhsNumber();
    }

    @Override
    public Date component9() {
        return getDateOfBirth();
    }

    @Override
    public Date component10() {
        return getDateOfDeath();
    }

    @Override
    public Long component11() {
        return getCurrentAddressId();
    }

    @Override
    public Integer component12() {
        return getEthnicCodeConceptId();
    }

    @Override
    public Long component13() {
        return getRegisteredPracticeOrganizationId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrganizationId();
    }

    @Override
    public Long value3() {
        return getPersonId();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getFirstNames();
    }

    @Override
    public String value6() {
        return getLastName();
    }

    @Override
    public Integer value7() {
        return getGenderConceptId();
    }

    @Override
    public String value8() {
        return getNhsNumber();
    }

    @Override
    public Date value9() {
        return getDateOfBirth();
    }

    @Override
    public Date value10() {
        return getDateOfDeath();
    }

    @Override
    public Long value11() {
        return getCurrentAddressId();
    }

    @Override
    public Integer value12() {
        return getEthnicCodeConceptId();
    }

    @Override
    public Long value13() {
        return getRegisteredPracticeOrganizationId();
    }

    @Override
    public PatientRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PatientRecord value2(Long value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public PatientRecord value3(Long value) {
        setPersonId(value);
        return this;
    }

    @Override
    public PatientRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PatientRecord value5(String value) {
        setFirstNames(value);
        return this;
    }

    @Override
    public PatientRecord value6(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public PatientRecord value7(Integer value) {
        setGenderConceptId(value);
        return this;
    }

    @Override
    public PatientRecord value8(String value) {
        setNhsNumber(value);
        return this;
    }

    @Override
    public PatientRecord value9(Date value) {
        setDateOfBirth(value);
        return this;
    }

    @Override
    public PatientRecord value10(Date value) {
        setDateOfDeath(value);
        return this;
    }

    @Override
    public PatientRecord value11(Long value) {
        setCurrentAddressId(value);
        return this;
    }

    @Override
    public PatientRecord value12(Integer value) {
        setEthnicCodeConceptId(value);
        return this;
    }

    @Override
    public PatientRecord value13(Long value) {
        setRegisteredPracticeOrganizationId(value);
        return this;
    }

    @Override
    public PatientRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, Integer value7, String value8, Date value9, Date value10, Long value11, Integer value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientRecord
     */
    public PatientRecord() {
        super(Patient.PATIENT);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(Long id, Long organizationId, Long personId, String title, String firstNames, String lastName, Integer genderConceptId, String nhsNumber, Date dateOfBirth, Date dateOfDeath, Long currentAddressId, Integer ethnicCodeConceptId, Long registeredPracticeOrganizationId) {
        super(Patient.PATIENT);

        set(0, id);
        set(1, organizationId);
        set(2, personId);
        set(3, title);
        set(4, firstNames);
        set(5, lastName);
        set(6, genderConceptId);
        set(7, nhsNumber);
        set(8, dateOfBirth);
        set(9, dateOfDeath);
        set(10, currentAddressId);
        set(11, ethnicCodeConceptId);
        set(12, registeredPracticeOrganizationId);
    }
}
