/*
 * This file is generated by jOOQ.
 */
package org.endeavour.queryengine.db.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.endeavour.queryengine.db.tables.Person;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonRecord extends UpdatableRecordImpl<PersonRecord> implements Record12<Long, Long, String, String, String, Integer, String, Date, Date, Long, Integer, Long> {

    private static final long serialVersionUID = -1047047181;

    /**
     * Setter for <code>subscriber_pi.person.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>subscriber_pi.person.organization_id</code>.
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.organization_id</code>.
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>subscriber_pi.person.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>subscriber_pi.person.first_names</code>.
     */
    public void setFirstNames(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.first_names</code>.
     */
    public String getFirstNames() {
        return (String) get(3);
    }

    /**
     * Setter for <code>subscriber_pi.person.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>subscriber_pi.person.gender_concept_id</code>.
     */
    public void setGenderConceptId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.gender_concept_id</code>.
     */
    public Integer getGenderConceptId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>subscriber_pi.person.nhs_number</code>.
     */
    public void setNhsNumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.nhs_number</code>.
     */
    public String getNhsNumber() {
        return (String) get(6);
    }

    /**
     * Setter for <code>subscriber_pi.person.date_of_birth</code>.
     */
    public void setDateOfBirth(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.date_of_birth</code>.
     */
    public Date getDateOfBirth() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>subscriber_pi.person.date_of_death</code>.
     */
    public void setDateOfDeath(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.date_of_death</code>.
     */
    public Date getDateOfDeath() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>subscriber_pi.person.current_address_id</code>.
     */
    public void setCurrentAddressId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.current_address_id</code>.
     */
    public Long getCurrentAddressId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>subscriber_pi.person.ethnic_code_concept_id</code>.
     */
    public void setEthnicCodeConceptId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.ethnic_code_concept_id</code>.
     */
    public Integer getEthnicCodeConceptId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>subscriber_pi.person.registered_practice_organization_id</code>.
     */
    public void setRegisteredPracticeOrganizationId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>subscriber_pi.person.registered_practice_organization_id</code>.
     */
    public Long getRegisteredPracticeOrganizationId() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, String, String, String, Integer, String, Date, Date, Long, Integer, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, String, String, String, Integer, String, Date, Date, Long, Integer, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Person.PERSON.ID;
    }

    @Override
    public Field<Long> field2() {
        return Person.PERSON.ORGANIZATION_ID;
    }

    @Override
    public Field<String> field3() {
        return Person.PERSON.TITLE;
    }

    @Override
    public Field<String> field4() {
        return Person.PERSON.FIRST_NAMES;
    }

    @Override
    public Field<String> field5() {
        return Person.PERSON.LAST_NAME;
    }

    @Override
    public Field<Integer> field6() {
        return Person.PERSON.GENDER_CONCEPT_ID;
    }

    @Override
    public Field<String> field7() {
        return Person.PERSON.NHS_NUMBER;
    }

    @Override
    public Field<Date> field8() {
        return Person.PERSON.DATE_OF_BIRTH;
    }

    @Override
    public Field<Date> field9() {
        return Person.PERSON.DATE_OF_DEATH;
    }

    @Override
    public Field<Long> field10() {
        return Person.PERSON.CURRENT_ADDRESS_ID;
    }

    @Override
    public Field<Integer> field11() {
        return Person.PERSON.ETHNIC_CODE_CONCEPT_ID;
    }

    @Override
    public Field<Long> field12() {
        return Person.PERSON.REGISTERED_PRACTICE_ORGANIZATION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrganizationId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getFirstNames();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public Integer component6() {
        return getGenderConceptId();
    }

    @Override
    public String component7() {
        return getNhsNumber();
    }

    @Override
    public Date component8() {
        return getDateOfBirth();
    }

    @Override
    public Date component9() {
        return getDateOfDeath();
    }

    @Override
    public Long component10() {
        return getCurrentAddressId();
    }

    @Override
    public Integer component11() {
        return getEthnicCodeConceptId();
    }

    @Override
    public Long component12() {
        return getRegisteredPracticeOrganizationId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrganizationId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getFirstNames();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public Integer value6() {
        return getGenderConceptId();
    }

    @Override
    public String value7() {
        return getNhsNumber();
    }

    @Override
    public Date value8() {
        return getDateOfBirth();
    }

    @Override
    public Date value9() {
        return getDateOfDeath();
    }

    @Override
    public Long value10() {
        return getCurrentAddressId();
    }

    @Override
    public Integer value11() {
        return getEthnicCodeConceptId();
    }

    @Override
    public Long value12() {
        return getRegisteredPracticeOrganizationId();
    }

    @Override
    public PersonRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PersonRecord value2(Long value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public PersonRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PersonRecord value4(String value) {
        setFirstNames(value);
        return this;
    }

    @Override
    public PersonRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public PersonRecord value6(Integer value) {
        setGenderConceptId(value);
        return this;
    }

    @Override
    public PersonRecord value7(String value) {
        setNhsNumber(value);
        return this;
    }

    @Override
    public PersonRecord value8(Date value) {
        setDateOfBirth(value);
        return this;
    }

    @Override
    public PersonRecord value9(Date value) {
        setDateOfDeath(value);
        return this;
    }

    @Override
    public PersonRecord value10(Long value) {
        setCurrentAddressId(value);
        return this;
    }

    @Override
    public PersonRecord value11(Integer value) {
        setEthnicCodeConceptId(value);
        return this;
    }

    @Override
    public PersonRecord value12(Long value) {
        setRegisteredPracticeOrganizationId(value);
        return this;
    }

    @Override
    public PersonRecord values(Long value1, Long value2, String value3, String value4, String value5, Integer value6, String value7, Date value8, Date value9, Long value10, Integer value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonRecord
     */
    public PersonRecord() {
        super(Person.PERSON);
    }

    /**
     * Create a detached, initialised PersonRecord
     */
    public PersonRecord(Long id, Long organizationId, String title, String firstNames, String lastName, Integer genderConceptId, String nhsNumber, Date dateOfBirth, Date dateOfDeath, Long currentAddressId, Integer ethnicCodeConceptId, Long registeredPracticeOrganizationId) {
        super(Person.PERSON);

        set(0, id);
        set(1, organizationId);
        set(2, title);
        set(3, firstNames);
        set(4, lastName);
        set(5, genderConceptId);
        set(6, nhsNumber);
        set(7, dateOfBirth);
        set(8, dateOfDeath);
        set(9, currentAddressId);
        set(10, ethnicCodeConceptId);
        set(11, registeredPracticeOrganizationId);
    }
}
