/*
 * This file is generated by jOOQ.
 */
package org.endeavour.queryengine.db.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.endeavour.queryengine.db.tables.ReferralRequest;
import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Record3;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferralRequestRecord extends UpdatableRecordImpl<ReferralRequestRecord> implements Record18<Long, Long, Long, Long, Long, Long, Date, Integer, Long, Long, Integer, Integer, String, Byte, Byte, Integer, Integer, BigDecimal> {

    private static final long serialVersionUID = -151247165;

    /**
     * Setter for <code>subscriber_pi.referral_request.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.organization_id</code>.
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.organization_id</code>.
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.encounter_id</code>.
     */
    public void setEncounterId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.encounter_id</code>.
     */
    public Long getEncounterId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.practitioner_id</code>.
     */
    public void setPractitionerId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.practitioner_id</code>.
     */
    public Long getPractitionerId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.clinical_effective_date</code>.
     */
    public void setClinicalEffectiveDate(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.clinical_effective_date</code>.
     */
    public Date getClinicalEffectiveDate() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.date_precision_concept_id</code>.
     */
    public void setDatePrecisionConceptId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.date_precision_concept_id</code>.
     */
    public Integer getDatePrecisionConceptId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.requester_organization_id</code>.
     */
    public void setRequesterOrganizationId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.requester_organization_id</code>.
     */
    public Long getRequesterOrganizationId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.recipient_organization_id</code>.
     */
    public void setRecipientOrganizationId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.recipient_organization_id</code>.
     */
    public Long getRecipientOrganizationId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.referral_request_priority_concept_id</code>.
     */
    public void setReferralRequestPriorityConceptId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.referral_request_priority_concept_id</code>.
     */
    public Integer getReferralRequestPriorityConceptId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.referral_request_type_concept_id</code>.
     */
    public void setReferralRequestTypeConceptId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.referral_request_type_concept_id</code>.
     */
    public Integer getReferralRequestTypeConceptId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.mode</code>.
     */
    public void setMode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.mode</code>.
     */
    public String getMode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.outgoing_referral</code>.
     */
    public void setOutgoingReferral(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.outgoing_referral</code>.
     */
    public Byte getOutgoingReferral() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.is_review</code>.
     */
    public void setIsReview(Byte value) {
        set(14, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.is_review</code>.
     */
    public Byte getIsReview() {
        return (Byte) get(14);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.core_concept_id</code>.
     */
    public void setCoreConceptId(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.core_concept_id</code>.
     */
    public Integer getCoreConceptId() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.non_core_concept_id</code>.
     */
    public void setNonCoreConceptId(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.non_core_concept_id</code>.
     */
    public Integer getNonCoreConceptId() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>subscriber_pi.referral_request.age_at_event</code>.
     */
    public void setAgeAtEvent(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>subscriber_pi.referral_request.age_at_event</code>.
     */
    public BigDecimal getAgeAtEvent() {
        return (BigDecimal) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, Long, Long, Long, Long, Long, Date, Integer, Long, Long, Integer, Integer, String, Byte, Byte, Integer, Integer, BigDecimal> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, Long, Long, Long, Long, Long, Date, Integer, Long, Long, Integer, Integer, String, Byte, Byte, Integer, Integer, BigDecimal> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ReferralRequest.REFERRAL_REQUEST.ID;
    }

    @Override
    public Field<Long> field2() {
        return ReferralRequest.REFERRAL_REQUEST.ORGANIZATION_ID;
    }

    @Override
    public Field<Long> field3() {
        return ReferralRequest.REFERRAL_REQUEST.PATIENT_ID;
    }

    @Override
    public Field<Long> field4() {
        return ReferralRequest.REFERRAL_REQUEST.PERSON_ID;
    }

    @Override
    public Field<Long> field5() {
        return ReferralRequest.REFERRAL_REQUEST.ENCOUNTER_ID;
    }

    @Override
    public Field<Long> field6() {
        return ReferralRequest.REFERRAL_REQUEST.PRACTITIONER_ID;
    }

    @Override
    public Field<Date> field7() {
        return ReferralRequest.REFERRAL_REQUEST.CLINICAL_EFFECTIVE_DATE;
    }

    @Override
    public Field<Integer> field8() {
        return ReferralRequest.REFERRAL_REQUEST.DATE_PRECISION_CONCEPT_ID;
    }

    @Override
    public Field<Long> field9() {
        return ReferralRequest.REFERRAL_REQUEST.REQUESTER_ORGANIZATION_ID;
    }

    @Override
    public Field<Long> field10() {
        return ReferralRequest.REFERRAL_REQUEST.RECIPIENT_ORGANIZATION_ID;
    }

    @Override
    public Field<Integer> field11() {
        return ReferralRequest.REFERRAL_REQUEST.REFERRAL_REQUEST_PRIORITY_CONCEPT_ID;
    }

    @Override
    public Field<Integer> field12() {
        return ReferralRequest.REFERRAL_REQUEST.REFERRAL_REQUEST_TYPE_CONCEPT_ID;
    }

    @Override
    public Field<String> field13() {
        return ReferralRequest.REFERRAL_REQUEST.MODE;
    }

    @Override
    public Field<Byte> field14() {
        return ReferralRequest.REFERRAL_REQUEST.OUTGOING_REFERRAL;
    }

    @Override
    public Field<Byte> field15() {
        return ReferralRequest.REFERRAL_REQUEST.IS_REVIEW;
    }

    @Override
    public Field<Integer> field16() {
        return ReferralRequest.REFERRAL_REQUEST.CORE_CONCEPT_ID;
    }

    @Override
    public Field<Integer> field17() {
        return ReferralRequest.REFERRAL_REQUEST.NON_CORE_CONCEPT_ID;
    }

    @Override
    public Field<BigDecimal> field18() {
        return ReferralRequest.REFERRAL_REQUEST.AGE_AT_EVENT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrganizationId();
    }

    @Override
    public Long component3() {
        return getPatientId();
    }

    @Override
    public Long component4() {
        return getPersonId();
    }

    @Override
    public Long component5() {
        return getEncounterId();
    }

    @Override
    public Long component6() {
        return getPractitionerId();
    }

    @Override
    public Date component7() {
        return getClinicalEffectiveDate();
    }

    @Override
    public Integer component8() {
        return getDatePrecisionConceptId();
    }

    @Override
    public Long component9() {
        return getRequesterOrganizationId();
    }

    @Override
    public Long component10() {
        return getRecipientOrganizationId();
    }

    @Override
    public Integer component11() {
        return getReferralRequestPriorityConceptId();
    }

    @Override
    public Integer component12() {
        return getReferralRequestTypeConceptId();
    }

    @Override
    public String component13() {
        return getMode();
    }

    @Override
    public Byte component14() {
        return getOutgoingReferral();
    }

    @Override
    public Byte component15() {
        return getIsReview();
    }

    @Override
    public Integer component16() {
        return getCoreConceptId();
    }

    @Override
    public Integer component17() {
        return getNonCoreConceptId();
    }

    @Override
    public BigDecimal component18() {
        return getAgeAtEvent();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrganizationId();
    }

    @Override
    public Long value3() {
        return getPatientId();
    }

    @Override
    public Long value4() {
        return getPersonId();
    }

    @Override
    public Long value5() {
        return getEncounterId();
    }

    @Override
    public Long value6() {
        return getPractitionerId();
    }

    @Override
    public Date value7() {
        return getClinicalEffectiveDate();
    }

    @Override
    public Integer value8() {
        return getDatePrecisionConceptId();
    }

    @Override
    public Long value9() {
        return getRequesterOrganizationId();
    }

    @Override
    public Long value10() {
        return getRecipientOrganizationId();
    }

    @Override
    public Integer value11() {
        return getReferralRequestPriorityConceptId();
    }

    @Override
    public Integer value12() {
        return getReferralRequestTypeConceptId();
    }

    @Override
    public String value13() {
        return getMode();
    }

    @Override
    public Byte value14() {
        return getOutgoingReferral();
    }

    @Override
    public Byte value15() {
        return getIsReview();
    }

    @Override
    public Integer value16() {
        return getCoreConceptId();
    }

    @Override
    public Integer value17() {
        return getNonCoreConceptId();
    }

    @Override
    public BigDecimal value18() {
        return getAgeAtEvent();
    }

    @Override
    public ReferralRequestRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value2(Long value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value3(Long value) {
        setPatientId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value4(Long value) {
        setPersonId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value5(Long value) {
        setEncounterId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value6(Long value) {
        setPractitionerId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value7(Date value) {
        setClinicalEffectiveDate(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value8(Integer value) {
        setDatePrecisionConceptId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value9(Long value) {
        setRequesterOrganizationId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value10(Long value) {
        setRecipientOrganizationId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value11(Integer value) {
        setReferralRequestPriorityConceptId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value12(Integer value) {
        setReferralRequestTypeConceptId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value13(String value) {
        setMode(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value14(Byte value) {
        setOutgoingReferral(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value15(Byte value) {
        setIsReview(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value16(Integer value) {
        setCoreConceptId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value17(Integer value) {
        setNonCoreConceptId(value);
        return this;
    }

    @Override
    public ReferralRequestRecord value18(BigDecimal value) {
        setAgeAtEvent(value);
        return this;
    }

    @Override
    public ReferralRequestRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6, Date value7, Integer value8, Long value9, Long value10, Integer value11, Integer value12, String value13, Byte value14, Byte value15, Integer value16, Integer value17, BigDecimal value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReferralRequestRecord
     */
    public ReferralRequestRecord() {
        super(ReferralRequest.REFERRAL_REQUEST);
    }

    /**
     * Create a detached, initialised ReferralRequestRecord
     */
    public ReferralRequestRecord(Long id, Long organizationId, Long patientId, Long personId, Long encounterId, Long practitionerId, Date clinicalEffectiveDate, Integer datePrecisionConceptId, Long requesterOrganizationId, Long recipientOrganizationId, Integer referralRequestPriorityConceptId, Integer referralRequestTypeConceptId, String mode, Byte outgoingReferral, Byte isReview, Integer coreConceptId, Integer nonCoreConceptId, BigDecimal ageAtEvent) {
        super(ReferralRequest.REFERRAL_REQUEST);

        set(0, id);
        set(1, organizationId);
        set(2, patientId);
        set(3, personId);
        set(4, encounterId);
        set(5, practitionerId);
        set(6, clinicalEffectiveDate);
        set(7, datePrecisionConceptId);
        set(8, requesterOrganizationId);
        set(9, recipientOrganizationId);
        set(10, referralRequestPriorityConceptId);
        set(11, referralRequestTypeConceptId);
        set(12, mode);
        set(13, outgoingReferral);
        set(14, isReview);
        set(15, coreConceptId);
        set(16, nonCoreConceptId);
        set(17, ageAtEvent);
    }
}
