/*
 * This file is generated by jOOQ.
 */
package org.endeavour.queryengine.db.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.endeavour.queryengine.db.tables.Schedule;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleRecord extends UpdatableRecordImpl<ScheduleRecord> implements Record7<Long, Long, Long, Date, String, String, String> {

    private static final long serialVersionUID = 725828210;

    /**
     * Setter for <code>subscriber_pi.schedule.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>subscriber_pi.schedule.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>subscriber_pi.schedule.organization_id</code>.
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>subscriber_pi.schedule.organization_id</code>.
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>subscriber_pi.schedule.practitioner_id</code>.
     */
    public void setPractitionerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>subscriber_pi.schedule.practitioner_id</code>.
     */
    public Long getPractitionerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>subscriber_pi.schedule.start_date</code>.
     */
    public void setStartDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>subscriber_pi.schedule.start_date</code>.
     */
    public Date getStartDate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>subscriber_pi.schedule.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>subscriber_pi.schedule.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>subscriber_pi.schedule.location</code>.
     */
    public void setLocation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>subscriber_pi.schedule.location</code>.
     */
    public String getLocation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>subscriber_pi.schedule.name</code>.
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>subscriber_pi.schedule.name</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Date, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Date, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Schedule.SCHEDULE.ID;
    }

    @Override
    public Field<Long> field2() {
        return Schedule.SCHEDULE.ORGANIZATION_ID;
    }

    @Override
    public Field<Long> field3() {
        return Schedule.SCHEDULE.PRACTITIONER_ID;
    }

    @Override
    public Field<Date> field4() {
        return Schedule.SCHEDULE.START_DATE;
    }

    @Override
    public Field<String> field5() {
        return Schedule.SCHEDULE.TYPE;
    }

    @Override
    public Field<String> field6() {
        return Schedule.SCHEDULE.LOCATION;
    }

    @Override
    public Field<String> field7() {
        return Schedule.SCHEDULE.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrganizationId();
    }

    @Override
    public Long component3() {
        return getPractitionerId();
    }

    @Override
    public Date component4() {
        return getStartDate();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getLocation();
    }

    @Override
    public String component7() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrganizationId();
    }

    @Override
    public Long value3() {
        return getPractitionerId();
    }

    @Override
    public Date value4() {
        return getStartDate();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getLocation();
    }

    @Override
    public String value7() {
        return getName();
    }

    @Override
    public ScheduleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ScheduleRecord value2(Long value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public ScheduleRecord value3(Long value) {
        setPractitionerId(value);
        return this;
    }

    @Override
    public ScheduleRecord value4(Date value) {
        setStartDate(value);
        return this;
    }

    @Override
    public ScheduleRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public ScheduleRecord value6(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public ScheduleRecord value7(String value) {
        setName(value);
        return this;
    }

    @Override
    public ScheduleRecord values(Long value1, Long value2, Long value3, Date value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduleRecord
     */
    public ScheduleRecord() {
        super(Schedule.SCHEDULE);
    }

    /**
     * Create a detached, initialised ScheduleRecord
     */
    public ScheduleRecord(Long id, Long organizationId, Long practitionerId, Date startDate, String type, String location, String name) {
        super(Schedule.SCHEDULE);

        set(0, id);
        set(1, organizationId);
        set(2, practitionerId);
        set(3, startDate);
        set(4, type);
        set(5, location);
        set(6, name);
    }
}
